"""Constants for coderev."""

SERVER_PORT = 8976
HEALTH_POLL_INTERVAL = 3
HEALTH_POLL_TIMEOUT = 120
CODESPACE_POLL_INTERVAL = 5
CODESPACE_BOOT_TIMEOUT = 300
CODESPACE_IDLE_TIMEOUT_MINUTES = 30
ASK_TIMEOUT = 130  # slightly above server-side 120s
MACHINE_TYPE = "basicLinux32gb"  # 2-core, good enough for Claude
